### ISSUE TITLE
thread panicked after running for hours

### ISSUE THREAD

**Issue by solopine** [6block/zkwork_aleo_gpu_worker#10]
I ran run_prover.sh with 2 NVIDIA 3080 for about 5 hours, then I found an error in log, and no more computing power output after then.

The error log is:

+-------------------------------------------------------------------------------------------+
| 2024-09-13T03:39:44                                                                       |
|                                                                                           |
| gpu[0]: (1m - 244173    5m - 282795    15m - 289480    30m - 333256    60m - 351461  )    |
| gpu[1]: (1m - 241388    5m - 279453    15m - 286633    30m - 329449    60m - 347391  )    |
| gpu[*]: (1m - 485561    5m - 562249    15m - 576113    30m - 662705    60m - 698852  )    |
|                                                                                           |
+-------------------------------------------------------------------------------------------+

^[[2m2024-09-13T03:39:44.215820^[[0m ^[[32m INFO^[[0m Gpu 1 start a new job 91
^[[2m2024-09-13T03:39:44.221513^[[0m ^[[32m INFO^[[0m Gpu 0 start a new job 91
Failed to alloc gpu resource for leaf array buffer. Exception:Failed to allocate gpu resource for leaf array.
thread '<unnamed>' panicked at src/main.rs:213:88:
called `Result::unwrap()` on an `Err` value: Failed to alloc and init leaf array buffer
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Failed to alloc gpu resource for leaf array buffer. Exception:Failed to allocate gpu resource for leaf array.
thread '<unnamed>' panicked at src/main.rs:213:88:
called `Result::unwrap()` on an `Err` value: Failed to alloc and init leaf array buffer

+-------------------------------------------------------------------------------------------+
| 2024-09-13T03:40:44                                                                       |
|                                                                                           |
| gpu[0]: (1m - N/A       5m - 224305    15m - 269735    30m - 320165    60m - 345178  )    |
| gpu[1]: (1m - N/A       5m - 221705    15m - 266950    30m - 316358    60m - 341155  )    |
| gpu[*]: (1m - N/A       5m - 446011    15m - 536686    30m - 636524    60m - 686334  )    |
|                                                                                           |
+-------------------------------------------------------------------------------------------+

**Comment by shannon-6block** [comment]
solved in release v0.1.2
