### ISSUE TITLE
Segmentation fault      (core dumped) 

### ISSUE THREAD

**Issue by markel987** [6block/zkwork_aleo_gpu_worker#11]
When I ran it for a while, sometimes for a few minutes, sometimes for several hours, it core dumped.
The following is error message:
/workspace/start.sh: line 8:    27 Segmentation fault      (core dumped) aleo_prover --address $addr --pool $pool --custom_name my1234 &> /workspace/run.log

**Comment by shannon-6block** [comment]
solved in release v0.1.2
