### ISSUE TITLE
Failed to create aleo prover. Exception:the provided PTX was compiled with an unsupported toolchain.

### ISSUE THREAD

**Issue by chenchen0611** [6block/zkwork_aleo_gpu_worker#13]
The graphics card is 4090 and the following error occurs with aleo_prover v0.1.3-boost，stable version is fine but the computing power is very low.

## Error info:
**Failed to create aleo prover. Exception:the provided PTX was compiled with an unsupported toolchain.
thread '<unnamed>' panicked at src/main.rs:205:30:
Failed to create GpuPuzzle: Failed to create aleo prover
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Failed to create aleo prover. Exception:the provided PTX was compiled with an unsupported toolchain.
thread '<unnamed>' panicked at src/main.rs:205:30:
Failed to create GpuPuzzle: Failed to create aleo prover**

**Comment by shannon-6block** [comment]
nvidia-driver version >-=545.23.06 ?

**Comment by chenchen0611** [comment]
必须得是>545.23.06?我是535.183.01，在不能升级驱动版本的情况下，只能使用旧版本了吗？

**Comment by chenchen0611** [comment]
能不能搞一个535.183能用的高版本，我这没有sudo权限升级不了驱动

**Comment by shannon-6block** [comment]
try 0.2.0
