### ISSUE TITLE
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./aleo_prover)

### ISSUE THREAD

**Issue by conarsad** [6block/zkwork_aleo_gpu_worker#15]
./aleo_prover: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./aleo_prover)
running on lastest HiveOS

**Comment by shannon-6block** [comment]
try upgrading HiveOS or using the following command to install libc6
`apt update && apt upgrade && echo "deb http://cz.archive.ubuntu.com/ubuntu jammy main" >> /etc/apt/sources.list && apt update && apt install libc6 -y`

**Comment by Heymdale** [comment]
sudo echo "deb http://cz.archive.ubuntu.com/ubuntu jammy main" >> /etc/apt/sources.list && apt update && apt install libc6 -y 

the command helped
