### ISSUE TITLE
The printed logs quickly fill up the entire hard drive, causing the system to crash.

### ISSUE THREAD

**Issue by abitoverflow** [6block/zkwork_aleo_gpu_worker#16]
When the GPU encounters an illegal memory error, the printed logs quickly fill up the entire hard drive, causing the system to crash. Could you optimize the log printing issue when errors occur in the next version?

**Comment by shannon-6block** [comment]
I think we've fixed the memory error

**Comment by bu11ettrain** [comment]
The issue is not fixed
