### ISSUE TITLE
problem connect to pool

### ISSUE THREAD

**Issue by xR3PMz** [6block/zkwork_aleo_gpu_worker#25]
On some rigs the miner refuses to connect to the pool.
However, they have the same configuration.

I would like to take this opportunity to tell you that I am happy to use your miner, you are very efficient! 
Good job!

![Capture d’écran 2024-09-29 à 12 28 54](https://github.com/user-attachments/assets/34c913f5-52e1-4036-a1e6-63e7d7ccb638)
![Capture d’écran 2024-09-29 à 12 29 56](https://github.com/user-attachments/assets/43df6712-e0b3-4302-a725-100346b4f81d)

**Comment by DzT13** [comment]
what is qubic is idling ? did you mine qubic?

**Comment by xR3PMz** [comment]
> what is qubic is idling ? did you mine qubic?

--> Dual mine Qubic/Aleo: https://advanced-hash.ai/?page=tutorial&id=94

**Comment by shannon-6block** [comment]
We had a DNS config error yesterday. See the Discord announcement for detail: https://discord.com/channels/984349855617011712/992365740051136582/1289902501163827210

If this is not the reason, I have no idea.

**Comment by xR3PMz** [comment]
> We had a DNS config error yesterday. See the Discord announcement for detail: https://discord.com/channels/984349855617011712/992365740051136582/1289902501163827210
> 
> If this is not the reason, I have no idea.

It's probably because of that. Thank you for your response!
