### ISSUE TITLE
WSL ERROR

### ISSUE THREAD

**Issue by MetaInfinityGamer** [6block/zkwork_aleo_gpu_worker#26]
2024-09-29T23:36:35.814073  INFO Worker start. version(0.2.3-full) commit hash(a6458dc)
Failed to get count of cuda capable device. Exception:out of memory
thread 'main' panicked at src/main.rs:134:14:
Failed to get gpu number: Failed to get count of cuda capable device.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
root@DESKTOP-HU38EA1:/mnt/aleo_prover-v0.2.3_full/aleo_prover#

**Comment by shannon-6block** [comment]
We don't officially support Windows+WSL.
Looks like NVIDIA driver error.
