### ISSUE TITLE
GLIBC_2.29' not found (required by «/ale o_prover)

### ISSUE THREAD

**Issue by Abdullahsh12** [6block/zkwork_aleo_gpu_worker#30]
![IMG_2381](https://github.com/user-attachments/assets/20bde9f8-855b-44a4-a2cb-144fbb01e6d7)

hi, i have followed all the steps of setting up the flight sheet on hiveos, but as i hit lunch i face this error.. how can i solve it ?

**Comment by techtronic01** [comment]
Same issue for me.

**Comment by Abdullahsh12** [comment]
> Same issue for me.

I have managed to solve it by doing 2 things..
1- update the gpu drive 
2- most importantly update the hiveos image with this command (hive-replace --lis) then type (1) then (yes).

It should do u fine

**Comment by shannon-6block** [comment]
https://github.com/6block/zkwork_aleo_gpu_worker/blob/master/FAQ.md#q12-how-to-resolve-the-version-glibc_229-not-found-error
