### ISSUE TITLE
Miner error. Please help

### ISSUE THREAD

**Issue by kanav662** [6block/zkwork_aleo_gpu_worker#37]
GLIBC_2029 NOT FOUND 
GLIBC_2.28 NOT FOUND 

PLEASE HELP ME FIGURE THIS OUT
![PXL_20241007_183357500](https://github.com/user-attachments/assets/51fffcb8-a481-4f3c-85fc-2acb880048af)

**Comment by shannon-6block** [comment]
https://github.com/6block/zkwork_aleo_gpu_worker/blob/master/FAQ.md#q12-how-to-resolve-the-version-glibc_229-not-found-error
