### ISSUE TITLE
Hiiveos missplaced GPUs

### ISSUE THREAD

**Issue by Lysnyt** [6block/zkwork_aleo_gpu_worker#43]
Hi there, I noticed that the order of the cards does not correspond with the hashing speed.
I have two rigs, most gpus are the same (3080), but in one i have 2x 3070 and in other one one 3080ti. 
Same problem in both rigs..
![missplaced_gpus](https://github.com/user-attachments/assets/b15147b3-84f1-40a8-86e8-124c2e5d5eb6)

**Comment by mumu714** [comment]
This issue has been fixed in v0.2.4
