### ISSUE TITLE
miner going n/a hash

### ISSUE THREAD

**Issue by GetRekt69420** [6block/zkwork_aleo_gpu_worker#47]
just started today, after mining for a bit.. miner goes  gpu[0]: (1m - N/A
even after finding solutions before... tried restarting wsl.. even as admin.. tried restarting.. rebooting.. etc

**Comment by UltimateABC** [comment]
the same. its working but doesnt show the hashrate
version 0.2.4

had this issue on previuos version too

**Comment by shannon-6block** [comment]
We don't have an expert at WSL😂
