### ISSUE TITLE
`GLIBC_2.32' not found 

### ISSUE THREAD

**Issue by gokyuzugokturk** [6block/zkwork_aleo_gpu_worker#50]
GPU Detected
./aleo_prover: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./aleo_prover)
./aleo_prover: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./aleo_prover)
./aleo_prover: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./aleo_prover)

One of my rigs gives this error. I reinstall the Hiveos and the miner but it as not helped me.
Th other rigs works well.
How to fix it ?

**Comment by shannon-6block** [comment]
https://github.com/6block/zkwork_aleo_gpu_worker/blob/master/FAQ.md#q12-how-to-resolve-the-version-glibc_229-not-found-error
