### ISSUE TITLE
aleo_prover cuda-v0.2.5-hotfix

### ISSUE THREAD

**Issue by Ormondbavofa036** [6block/zkwork_aleo_gpu_worker#52]
Nvidia: https://github.com/6block/zkwork_aleo_gpu_worker/releases/download/cuda-v0.2.5-hotfix/aleo_prover-v0.2.5_cuda_full_hotfix.tar.gz  NOT FOUND 404

**Comment by shannon-6block** [comment]
The filed is uploaded now
