### ISSUE TITLE
cuda-v0.2.5

### ISSUE THREAD

**Issue by Ormondbavofa036** [6block/zkwork_aleo_gpu_worker#53]
Failed to find proof target. Exception:an illegal memory access was encountered                                                                                                                           
2024-11-19T17:59:02.668686  WARN Gpu 2 find proof target error: Failed find valid proof target in range 2031018369386170378 2031018369395607562
Failed to run epoch setup process. Exception:an illegal memory access was encountered                                                                                                                     
2024-11-19T17:59:02.668903 ERROR Gpu 5 epoch_setup: Failed to run epoch setup process, stop work 3.
terminate called after throwing an instance of 'cuda_helper::CudaException'                                                                                                                               
  what():  an illegal memory access was encountered

**Comment by shannon-6block** [comment]
It's supposed to be fixed here
https://github.com/6block/zkwork_aleo_gpu_worker/releases/tag/cuda-v0.2.5-hotfix
